// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAN7JxeLvhZgl6jMn5PYmdLD2HbYqvVULI',
    appId: '1:338757012859:web:3aa8d2571ff0d5fe2741de',
    messagingSenderId: '338757012859',
    projectId: 'myshop-75ac6',
    authDomain: 'myshop-75ac6.firebaseapp.com',
    storageBucket: 'myshop-75ac6.appspot.com',
    measurementId: 'G-WGKLKK3LZY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQhihdwZvavzkFc-mIcxboQEdtSFNueAI',
    appId: '1:338757012859:android:81f7433f06e18b082741de',
    messagingSenderId: '338757012859',
    projectId: 'myshop-75ac6',
    storageBucket: 'myshop-75ac6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMaWqTqCR4UJpJxEmx1xbR0fPVXqIcJdU',
    appId: '1:338757012859:ios:d5c0820a32866b902741de',
    messagingSenderId: '338757012859',
    projectId: 'myshop-75ac6',
    storageBucket: 'myshop-75ac6.appspot.com',
    iosBundleId: 'com.example.myshop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMaWqTqCR4UJpJxEmx1xbR0fPVXqIcJdU',
    appId: '1:338757012859:ios:d5c0820a32866b902741de',
    messagingSenderId: '338757012859',
    projectId: 'myshop-75ac6',
    storageBucket: 'myshop-75ac6.appspot.com',
    iosBundleId: 'com.example.myshop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAN7JxeLvhZgl6jMn5PYmdLD2HbYqvVULI',
    appId: '1:338757012859:web:17252029dab004d42741de',
    messagingSenderId: '338757012859',
    projectId: 'myshop-75ac6',
    authDomain: 'myshop-75ac6.firebaseapp.com',
    storageBucket: 'myshop-75ac6.appspot.com',
    measurementId: 'G-2LJYFNSMXL',
  );
}
